{% set version = "6.2.0" %}

package:
  name: traits
  version: {{ version }}

source:
  fn: traits-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/traits/traits-{{ version }}.tar.gz
  sha256: 16fa1518b0778fd53bf0547e6a562b1787bf68c8f6b7995a13bd1902529fdb0c

build:
  number: 0
  skip: true  # [py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
  run_constrained:
    - traitsui >=7.0

test:
  imports:
    - traits

about:
  home: http://code.enthought.com/projects/traits
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: traits - explicitly typed attributes for Python

extra:
  recipe-maintainers:
    - grlee77
