{% set version = "7.0.2" %}

package:
  name: traits
  version: {{ version }}

source:
  fn: traits-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/t/traits/traits-{{ version }}.tar.gz
  sha256: a563515809cb3911975de5a54209855f0b6fdb7ca6912a5e81de26529f70428c
  patches:
    # https://github.com/enthought/traits/pull/1767
    - 0001-Fix-Traits-build-error-on-Python-3.13-1767.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
  run_constrained:
    - traitsui >=7.0

test:
  imports:
    - traits

about:
  home: https://docs.enthought.com/traits
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: traits - explicitly typed attributes for Python

extra:
  recipe-maintainers:
    - grlee77
    - ericpre
