{% set version = "4.6.0" %}

package:
  name: traits
  version: {{ version }}

source:
  fn: traits-{{ version }}.tar.gz
  url: https://github.com/enthought/traits/archive/{{ version }}.tar.gz
  sha256: c2deacbdb2a42825e198b35f46af13625c820e00e000f2fde2187cdb12c870b9

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - traits

about:
  home: http://code.enthought.com/projects/traits
  license: BSD 3-clause
  summary: traits - explicitly typed attributes for Python

extra:
  recipe-maintainers:
    - grlee77
