{% set version = "6.4.2" %}

package:
  name: traits
  version: {{ version }}

source:
  fn: traits-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/traits/traits-{{ version }}.tar.gz
  sha256: 5be7cc5fb7a99cba7e9014786373e3ad2f75efb445eeced094654bbaf3b0fa82

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
  run_constrained:
    - traitsui >=7.0

test:
  imports:
    - traits

about:
  home: https://docs.enthought.com/traits
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: traits - explicitly typed attributes for Python

extra:
  recipe-maintainers:
    - grlee77
    - ericpre
